### PR TITLE
Enable Windows CI

### LINKED ISSUE #32: Add Windows & Appveyor CI support
## Issue / Feature Request Summary

It's time to add Windows as a supported OS.  There should be no technical limitation here beyond the difficulty of developing it without a Windows machine (relying instead on Appveyor directly).

At the moment, that failure due to lack of OS support (originally raised by @tomduff) is expressed in this form:
```
C:\User\someone\GitHub\arduino_ci\SampleProjects\DoSomething>bundle exec arduino_ci_remote.rb
Installing library under test... Traceback (most recent call last):
        5: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/bin/arduino_ci_remote.rb:23:in `<main>'
        4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/bin/arduino_ci_remote.rb:23:in `load'
        3: from C:/User/someone/Documents/GitHub/arduino_ci/exe/arduino_ci_remote.rb:66:in `<top (required)>'
        2: from C:/User/someone/Documents/GitHub/arduino_ci/exe/arduino_ci_remote.rb:58:in `assure'
        1: from C:/User/someone/Documents/GitHub/arduino_ci/exe/arduino_ci_remote.rb:32:in `perform_action'
C:/User/someone/GitHub/arduino_ci/exe/arduino_ci_remote.rb:66:in `block in <top (required)>': undefined method `install_local_library' for nil:NilClass (NoMethodError)
```

### LINKED ISSUE #41: Gemfile.lock files in SampleProjects directories aren't being ignored by git
## Code Illustrating the Problem

```
find . | grep Gemfile.lock | xargs -I% echo "git log %" | sh
```

### LINKED ISSUE #45: Suppress CLIXML output on Appveyor
## System

> Feel free to delete this section if you're submitting a feature request

- URL of CI job: https://ci.appveyor.com/project/ianfixes/arduino-ci/build/1.0.34#L143
- URL of your Arduino project:

## Issue Summary

There's an obscene amount of `CLIXML` text in [the output](https://ci.appveyor.com/project/ianfixes/arduino-ci/build/1.0.34#L143).  

> #< CLIXML
> <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">2</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="2"><TNRef RefId="0" /><MS><I64 N="SourceId">3</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="3"><TNRef RefId="0" /><MS><I64 N="SourceId">0</I64><PR N="Record"><AV>Expand-Archive</AV><AI>0</AI><Nil /><PI>-1</PI><PC>1</PC><T>Processing</T><SR>-1</SR><SD>The archive file 'arduino-1.8.5' expansion is in progress...</SD></PR></MS></Obj><Obj S="progress" RefId="4"><TNRef RefId="0" /><MS><I64 N="SourceId">0</I64><PR N="Record"><AV>Expand-Archive</AV><AI>0</AI><Nil /><PI>-1</PI><PC>0</PC><T>Processing</T><SR>-1</SR><SD>The archive file 'C:\projects\arduino-ci\arduino-1.8.5-windows.zip' expansion is in progress...</SD></PR></MS></Obj><Obj S="progress" RefId="5"><TNRef RefId="0" /><MS><I64 N="SourceId">0</I64><PR N="Record"><AV>Expand-Archive</AV><AI>0</AI><Nil /><PI>-1</PI><PC>0</PC><T>Processing</T><SR>-1</SR><SD>The archive file 'C:\projects\arduino-ci\arduino-1.8.5-windows.zip' expansion is in progress...</SD></PR></MS></Obj><Obj S="progress" RefId="6"><TNRef RefId="0" /><MS><I64 N="SourceId">0</I64><PR N="Record"><AV>Expand-Archive</AV><AI>0</AI><Nil /><PI>-1</PI><PC>0</PC><T>Processing</T><SR>-1</SR><SD>The archive file 'C:\projects\arduino-ci\arduino-1.8.5-windows.zip' expansion is in progress...</SD></PR></MS></Obj><Obj S="progress" RefId="7"><TNRef RefId="0" /><MS><I64 N="SourceId">0</I64><PR N="Record"><AV>Expand-Archive</AV><AI>0</AI><Nil /><PI>-1</PI><PC>0</PC><T>Processing</T><SR>-1</SR><SD>The archive file 'C:\projects\arduino-ci\arduino-1.8.5-windows.zip' expansion

We should suppress it.

### PR DESCRIPTION
**Pull request by ianfixes**
## Highlights from `CHANGELOG.md`

* See CHANGELOG.md for more

## Issues Fixed

* Fixes #32
* Fixes #41 
* Fixes #45

### CODE REVIEW

**Comment by ianfixes** [comment]
Punting #45 to future work

**Comment by ianfixes** [comment]
@tomduff if you do any future work on this branch, don't worry about rubocop errors!  I can tend to those for you.

**Comment by tomduff** [comment]
Issue #48 was inspired by my looking at the odd compilation error in wstring.cpp.

I discovered the following which might be useful:
 ```
  // Works just fine
  long v = -2147483648L;
  assertEqual(-2147483648L, v);
  assertEqual("-2147483648", String(v));
  assertEqual("-2147483648", String((long)-2147483648L));

  // Fails as expected since this blows out the long
  // v = -2147483649L;
  // assertEqual(-2147483648L, v);

  // Fails - not sure why ????
  // assertEqual("-2147483648", String(-2147483648L));
```

**Comment by ianfixes** [comment]
Thanks for your help on this @tomduff !

**Comment by tomduff** [comment]
@ianfixes No problem, glad I could assist.

Does the merge down to master mean a new version of the Gem will be published?

**Comment by ianfixes** [comment]
Soon.  I have a few stray things to clean up that are going in #50 but after that I'll roll it out.

**Comment by ianfixes** [comment]
If you hadn't already seen it, v0.1.10 is out with these fixes

**Pull request merged**
